### ISSUE TITLE
How to import this library?

### ISSUE THREAD

**Issue by GuillermoBaban** [josegoval/dni-nif-nie-validation#5]
Hola como se importa la libreria?

hi how import he library?

**Comment by josegoval** [comment]
`import { isValidNif } from "nif-dni-nie-cif-validation"`

I'll set an example in the readme later.

**Comment by josegoval** [comment]
A new section is added to the readme explaining how to import the package and use it: https://github.com/josegoval/nif-dni-nie-cif-validation/blob/main/README.md#example-usage

Ask anything else if you need it.

Thanks for the report.
